# Generated by Django 3.0.9 on 2020-08-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='customers/images')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date_registered')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Category')),
            ],
        ),
    ]
