# Generated by Django 3.0.9 on 2020-09-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://dummyimage.com/240x140/e3e3e3/000000.jpg', upload_to='products/images'),
        ),
    ]
